from __future__ import annotations

from typing import Any


LOGICAL_LAYER_VERSION = "m3.logical_layers.v3_l0_l16"


LOGICAL_LAYERS: list[dict[str, Any]] = [
    {
        "layer": "L0",
        "name": "Raw Source Unit Manifest",
        "old_layer": "L0",
        "physical_artifacts": ["l0/object_stream_manifest.json", "l0/source_manifest.json", "l0/replay_locator_index.json"],
        "one_line": "Preserve raw object/window identity, checksums, and replay locators without copying or transforming data.",
        "handoff_from": "M1 source registration",
        "handoff_to": "M3 L1 bronze envelope",
        "owner_scope": "M3 records source identity and replay contract only.",
    },
    {
        "layer": "L1",
        "name": "Bronze Envelope and Rescue Lane",
        "old_layer": "L1",
        "physical_artifacts": ["l1/bronze_envelope_samples.manifest.json", "l1/rescue_lane.manifest.json", "l1/bronze_envelope_spec.json"],
        "one_line": "Wrap bounded raw samples and parse failures so no unknown input is silently discarded.",
        "handoff_from": "M3 L0 raw manifest",
        "handoff_to": "M3 L2 profile snapshot",
        "owner_scope": "M3 defines envelope semantics; runtime ingestion remains outside M3 core.",
    },
    {
        "layer": "L2",
        "name": "Profile and Data Shape Snapshot",
        "old_layer": "L2",
        "physical_artifacts": ["l2/profile_snapshot.json", "l2/format_profile.json", "l2/schema_fingerprint.json"],
        "one_line": "Summarize CSV/JSON/JSONL structure, field types, shape class, parser stats, and bounded evidence limits.",
        "handoff_from": "M3 L1 samples",
        "handoff_to": "M3 L3 AI-safe evidence reduction",
        "owner_scope": "M3 profiles bounded evidence; full production metrics must come back from M2.",
    },
    {
        "layer": "L3",
        "name": "AI-Safe Evidence Reduction",
        "old_layer": "L3",
        "physical_artifacts": [
            "l3/ai_recommendation_input_pack.json",
            "l3/field_evidence_reducer.json",
            "l3/redaction_map.json",
            "l3/policy_context_pack.json",
            "l3/unknown_data_recommendation_pack.json",
        ],
        "one_line": "Reduce L2 profile into redacted bounded evidence that an AI/model can inspect without raw data-plane access.",
        "handoff_from": "M3 L2 profile/data-shape evidence",
        "handoff_to": "M3 L4 metadata and template retrieval",
        "owner_scope": "M3 controls AI input safety, PII redaction, and row-level AI prohibition.",
    },
    {
        "layer": "L4",
        "name": "Metadata and Template Retrieval",
        "old_layer": "L3A/L3B",
        "physical_artifacts": ["l3/metadata_retrieval_index_plan.json", "l3/gold_template_candidate_retrieval.json"],
        "one_line": "Search schema/profile/catalog evidence for compatible Gold templates without claiming execution correctness.",
        "handoff_from": "M3 L3 AI-safe evidence pack",
        "handoff_to": "M3 L5 candidate grounding gate",
        "owner_scope": "M3 recommends retrieval documents and template candidates; vector index execution is extension-owned.",
    },
    {
        "layer": "L5",
        "name": "Candidate Grounding Gate",
        "old_layer": "L3C",
        "physical_artifacts": ["l3/candidate_grounding_report.json"],
        "one_line": "Check whether retrieved Silver/Gold candidates have enough source evidence to become editable drafts.",
        "handoff_from": "M3 L4 template candidates",
        "handoff_to": "M3 L6/L7/L8 recommendation drafts",
        "owner_scope": "M3 blocks weak semantic claims such as conversion or late delivery metrics without denominators.",
    },
    {
        "layer": "L6",
        "name": "Silver Recommendation Draft",
        "old_layer": "L4-S",
        "physical_artifacts": ["l4/silver_policy_recommendation_draft.json"],
        "one_line": "Recommend deterministic Bronze-to-Silver cleaning, typing, masking, quarantine, and exposure policy.",
        "handoff_from": "M3 L3 evidence and L5 grounding",
        "handoff_to": "M3 L9 user decision",
        "owner_scope": "M3 drafts Silver policy; user/M5 approval is required before compile.",
    },
    {
        "layer": "L7",
        "name": "Gold Recommendation Draft",
        "old_layer": "L4-G",
        "physical_artifacts": [
            "l4/gold_model_recommendation_draft.json",
            "l4/product_health_gold_template_draft.json",
            "l4/risk_score_policy_recommendation_draft.json",
        ],
        "one_line": "Recommend optional Silver-to-Gold models, product-health templates, and source-adaptive risk score policy.",
        "handoff_from": "M3 L5 grounded candidates",
        "handoff_to": "M3 L9 user decision",
        "owner_scope": "M3 drafts Gold semantics only; Gold execution is never automatic.",
    },
    {
        "layer": "L8",
        "name": "Vector and Semantic Handoff Draft",
        "old_layer": "L4-V",
        "physical_artifacts": ["l4/vector_embedding_handoff_template.json", "l4/ai_generation_trace.json"],
        "one_line": "Draft safe schema/catalog/vector handoff metadata for M6 or vector extensions without building embeddings in M3.",
        "handoff_from": "M3 L3 evidence and L5 grounding",
        "handoff_to": "M3 L9 user decision or M6/vector extension approval",
        "owner_scope": "M3 proposes vector/search metadata; downstream systems build and serve indexes.",
    },
    {
        "layer": "L9",
        "name": "User Decision and Approval State",
        "old_layer": "L5",
        "physical_artifacts": [
            "l5/silver_policy_decision.json",
            "l5/gold_policy_decision.json",
            "l5/gold_to_gold_policy_decision.json",
            "l5/approval_state.json",
            "l5/recommendation_diff.json",
        ],
        "one_line": "Freeze user-edited decisions for Silver, optional Gold, Gold-to-Gold, risk policy, and vector handoff.",
        "handoff_from": "M1 UI edits and M5 approval state",
        "handoff_to": "M3 L10/L11/L12 compilers",
        "owner_scope": "M3 records decision contracts; M5 persists approval state.",
    },
    {
        "layer": "L10",
        "name": "Silver Deterministic Spec Compiler",
        "old_layer": "L6-S",
        "physical_artifacts": ["l6/silver_transform_spec.json"],
        "one_line": "Compile approved Silver decisions into preview-only declarative operations for M2 execution.",
        "handoff_from": "M3 L9 approved Silver decision",
        "handoff_to": "M2 preview execution and M3 L13 validation",
        "owner_scope": "M3 emits deterministic spec; M2 owns Spark/runtime execution.",
    },
    {
        "layer": "L11",
        "name": "Gold Deterministic Spec Compiler",
        "old_layer": "L6-G",
        "physical_artifacts": ["l6/gold_generation_spec.json"],
        "one_line": "Compile approved optional Gold decisions into preview-only aggregate/model operations.",
        "handoff_from": "M3 L9 approved Gold decision",
        "handoff_to": "M2 preview execution and M3 L14 readiness",
        "owner_scope": "M3 emits Gold spec only when approval allows it; deferred/not_requested stays non-executable.",
    },
    {
        "layer": "L12",
        "name": "Compiler Validation and Unsupported Action Gate",
        "old_layer": "L6-C",
        "physical_artifacts": [
            "l6/compiler_validation_result.json",
            "l6/unsupported_action_report.json",
            "l6/layered_transform_graph.json",
        ],
        "one_line": "Block unsafe specs such as row-level AI, generated code execution, unbounded collect, or production writes.",
        "handoff_from": "M3 L10/L11 compiled specs",
        "handoff_to": "M2 preview execution or M1/M5 decision repair",
        "owner_scope": "M3 validates compile contract safety, not production cluster behavior.",
    },
    {
        "layer": "L13",
        "name": "Silver Preview Evidence Gate",
        "old_layer": "L7",
        "physical_artifacts": [
            "l7/silver_preview_ref.json",
            "l7/silver_preview_validation_result.json",
            "l7/pii_exposure_report.json",
            "l7/silver_quality_axis.json",
            "l7/silver_quarantine_report.json",
        ],
        "one_line": "Validate Silver preview evidence, exposure controls, and quarantine structure returned from M2/local harness.",
        "handoff_from": "M2 preview metrics over M3 L10 spec",
        "handoff_to": "M3 L15 final gate",
        "owner_scope": "M3 evaluates imported evidence; it does not own distributed execution.",
    },
    {
        "layer": "L14",
        "name": "Gold Preview Readiness Gate",
        "old_layer": "L8",
        "physical_artifacts": [
            "l8/gold_preview_ref.json",
            "l8/metric_definition_draft.json",
            "l8/gold_readiness_input_report.json",
            "l8/gold_preview_validation_result.json",
            "l8/semantic_caveat_report.json",
        ],
        "one_line": "Validate optional Gold preview readiness, semantic caveats, metric definitions, and not_requested/deferred status.",
        "handoff_from": "M2 preview metrics over M3 L11 spec",
        "handoff_to": "M3 L15 final gate",
        "owner_scope": "M3 keeps Gold readiness separate from Silver readiness.",
    },
    {
        "layer": "L15",
        "name": "Three-Axis Readiness Gate",
        "old_layer": "L9",
        "physical_artifacts": [
            "l9/processing_quality_axis.json",
            "l9/catalog_safety_axis.json",
            "l9/gold_readiness_axis.json",
            "l9/gate_summary.json",
        ],
        "one_line": "Combine processing quality, catalog safety, and Gold readiness without letting Gold contaminate Silver status.",
        "handoff_from": "M3 L13 Silver evidence and L14 Gold evidence",
        "handoff_to": "M5 catalog state and M6 query context",
        "owner_scope": "M3 computes readiness semantics and caveats from imported execution evidence.",
    },
    {
        "layer": "L16",
        "name": "Catalog, Query, and Vector Handoff Package",
        "old_layer": "L10",
        "physical_artifacts": [
            "l10/catalog_sync_contract_package.json",
            "l10/catalog_metadata_draft.json",
            "l10/sql_context_pack.json",
            "l10/semantic_catalog_vector_index_template.json",
            "l10/artifact_reference_manifest.json",
            "exports/transform_spec.json",
            "exports/schema_definition.json",
            "exports/workflow_definition.json",
            "exports/catalog_metadata.json",
        ],
        "one_line": "Package artifact refs, catalog metadata, SQL context, lineage, and semantic/vector handoff for M5 and M6.",
        "handoff_from": "M3 L15 readiness gate",
        "handoff_to": "M5 catalog/workflow storage and M6 query context",
        "owner_scope": "M3 drafts handoff packages; M5/M6 persist, query, and serve them.",
    },
]


SPLIT_SUMMARY: list[dict[str, Any]] = [
    {
        "old_layer": "L3",
        "new_layers": ["L3", "L4", "L5"],
        "why": "AI-safe evidence, template retrieval, and grounding have different failure modes and should not be one stage.",
    },
    {
        "old_layer": "L4",
        "new_layers": ["L6", "L7", "L8"],
        "why": "Silver policy, Gold semantics, and vector handoff are edited and approved independently.",
    },
    {
        "old_layer": "L5",
        "new_layers": ["L9"],
        "why": "The decision stage remains one place but now approves split Silver, Gold, Gold-to-Gold, risk, and vector drafts.",
    },
    {
        "old_layer": "L6",
        "new_layers": ["L10", "L11", "L12"],
        "why": "Silver spec, Gold spec, and compiler safety validation must be inspectable separately.",
    },
    {
        "old_layer": "L7-L10",
        "new_layers": ["L13", "L14", "L15", "L16"],
        "why": "Preview evidence, readiness gates, and final catalog/query handoff remain explicit downstream stages.",
    },
]


_ARTIFACT_LOGICAL_LAYER = {
    ("l0", "object_stream_manifest"): "L0",
    ("l0", "source_manifest"): "L0",
    ("l0", "replay_locator_index"): "L0",
    ("l1", "bronze_envelope_samples"): "L1",
    ("l1", "rescue_lane"): "L1",
    ("l1", "bronze_envelope_spec"): "L1",
    ("l2", "profile_snapshot"): "L2",
    ("l2", "format_profile"): "L2",
    ("l2", "format_detection"): "L2",
    ("l2", "schema_fingerprint"): "L2",
    ("l3", "ai_recommendation_input_pack"): "L3",
    ("l3", "field_evidence_reducer"): "L3",
    ("l3", "redaction_map"): "L3",
    ("l3", "policy_context_pack"): "L3",
    ("l3", "unknown_data_recommendation_pack"): "L3",
    ("l3", "metadata_retrieval_index_plan"): "L4",
    ("l3", "gold_template_candidate_retrieval"): "L4",
    ("l3", "candidate_grounding_report"): "L5",
    ("l4", "silver_policy_recommendation_draft"): "L6",
    ("l4", "gold_model_recommendation_draft"): "L7",
    ("l4", "product_health_gold_template_draft"): "L7",
    ("l4", "risk_score_policy_recommendation_draft"): "L7",
    ("l4", "vector_embedding_handoff_template"): "L8",
    ("l4", "ai_generation_trace"): "L8",
    ("l5", "silver_policy_decision"): "L9",
    ("l5", "gold_policy_decision"): "L9",
    ("l5", "gold_to_gold_policy_decision"): "L9",
    ("l5", "approval_state"): "L9",
    ("l5", "recommendation_diff"): "L9",
    ("l6", "silver_transform_spec"): "L10",
    ("l6", "gold_generation_spec"): "L11",
    ("l6", "layered_transform_graph"): "L12",
    ("l6", "unsupported_action_report"): "L12",
    ("l6", "compiler_validation_result"): "L12",
    ("l7", "silver_preview"): "L13",
    ("l7", "silver_preview_validation_result"): "L13",
    ("l7", "pii_exposure_report"): "L13",
    ("l7", "silver_quality_axis"): "L13",
    ("l7", "silver_quarantine_report"): "L13",
    ("l8", "gold_preview"): "L14",
    ("l8", "metric_definition_draft"): "L14",
    ("l8", "gold_readiness_input_report"): "L14",
    ("l8", "gold_preview_validation_result"): "L14",
    ("l8", "semantic_caveat_report"): "L14",
    ("l9", "processing_quality_axis"): "L15",
    ("l9", "catalog_safety_axis"): "L15",
    ("l9", "gold_readiness_axis"): "L15",
    ("l9", "gate_summary"): "L15",
    ("l10", "catalog_metadata_draft"): "L16",
    ("l10", "sql_context_pack"): "L16",
    ("l10", "field_level_lineage"): "L16",
    ("l10", "catalog_sync_contract_package"): "L16",
    ("l10", "semantic_catalog_vector_index_template"): "L16",
    ("l10", "handoff_package"): "L16",
    ("l10", "artifact_reference_manifest"): "L16",
}


def logical_layer_for_artifact(layer: str, name: str) -> str:
    """Return the canonical L0-L16 logical layer for a backward-compatible artifact path."""

    normalized_layer = layer.lower()
    normalized_name = name.lower()
    if (normalized_layer, normalized_name) in _ARTIFACT_LOGICAL_LAYER:
        return _ARTIFACT_LOGICAL_LAYER[(normalized_layer, normalized_name)]
    if normalized_layer.startswith("l") and normalized_layer[1:].isdigit():
        return normalized_layer.upper()
    return "UNKNOWN"
