import { useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import {
  ArrowLeft,
  BarChart3,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Clipboard,
  Database,
  FileText,
  GitBranch,
  Layers3,
  Search,
  Sparkles,
} from "lucide-react";
import { useToast } from "../../components/common/Toast";
import DemoInsightChart from "../query/components/DemoInsightChart";
import {
  formatDateLabel,
  formatMetricValue,
  getDashboardState,
  getInsightMetricKeys,
  getInsightMetricLabels,
} from "../query/demoAiQueryData";

function getSourceMeta(board) {
  const table = board.sourceTable || board.source?.split("/").pop()?.trim() || "orders";
  return {
    provider: board.sourceType || "Supabase",
    table,
    rowCount: table === "customers" ? "32,480" : "1,248",
    status: "Connected",
    lastQueriedAt: board.updatedAt || board.createdAt,
  };
}

export default function DashboardInsightDetailPage() {
  const { insightId } = useParams();
  const navigate = useNavigate();
  const { showToast } = useToast();
  const [showSql, setShowSql] = useState(false);
  const [showRawData, setShowRawData] = useState(false);
  const [copied, setCopied] = useState(false);

  const board = useMemo(() => {
    const state = getDashboardState();
    return state.boards.find((item) => item.id === insightId);
  }, [insightId]);

  if (!board) {
    return (
      <div className="h-full min-h-0 overflow-y-auto bg-gray-50 p-6">
        <div className="mx-auto max-w-4xl rounded-lg border border-gray-200 bg-white p-8 text-center shadow-sm">
          <BarChart3 className="mx-auto h-10 w-10 text-gray-300" />
          <h1 className="mt-4 text-lg font-semibold text-gray-900">
            분석 결과를 찾을 수 없습니다.
          </h1>
          <button
            onClick={() => navigate("/dashboard")}
            className="mt-5 rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
          >
            Dashboard로 돌아가기
          </button>
        </div>
      </div>
    );
  }

  const metricKeys = getInsightMetricKeys(board);
  const metricLabels = getInsightMetricLabels(board);
  const latestRow = board.chartData[board.chartData.length - 1];
  const sourceMeta = getSourceMeta(board);
  const ragEvidence = board.ragEvidence || [];
  const chunkingItems = board.chunkingStrategy?.items || [];
  const pipeline = board.pipeline || [
    {
      title: "1. 데이터 소스",
      body: `${sourceMeta.provider} / ${sourceMeta.table}`,
    },
    {
      title: "2. SQL 쿼리",
      body: "Read Only · 실행 성공",
    },
    {
      title: "3. AI 분석",
      body: "질문 해석 및 인사이트 생성",
    },
    {
      title: "4. 최종 차트",
      body: "Generated Chart",
    },
  ];

  const handleCopySql = async () => {
    await navigator.clipboard.writeText(board.sql);
    setCopied(true);
    showToast("SQL을 복사했습니다", "success");
    window.setTimeout(() => setCopied(false), 1400);
  };

  const rawColumns = Object.keys(board.rawData?.[0] || board.chartData?.[0] || {});
  const rawRows = board.rawData?.length ? board.rawData : board.chartData;

  return (
    <div className="h-full min-h-0 overflow-y-auto bg-gray-50 p-4 sm:p-6">
      <div className="mx-auto max-w-7xl space-y-5">
        <header className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm">
          <button
            onClick={() => navigate("/dashboard")}
            className="inline-flex items-center gap-2 text-sm font-medium text-gray-600 hover:text-gray-900"
          >
            <ArrowLeft className="h-4 w-4" />
            Dashboard로 돌아가기
          </button>

          <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <div className="flex flex-wrap items-center gap-2">
                <h1 className="text-2xl font-semibold text-gray-900">
                  {board.title}
                </h1>
                <span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-medium text-indigo-700">
                  {ragEvidence.length > 0 ? "SQL + RAG" : "Generated by AI"}
                </span>
                {ragEvidence.length > 0 && (
                  <span className="rounded-full bg-orange-50 px-2.5 py-1 text-xs font-medium text-orange-700">
                    근거 chunk {ragEvidence.length}개
                  </span>
                )}
              </div>
              <p className="mt-2 text-sm text-gray-500">{board.description}</p>
            </div>
            <div className="text-sm text-gray-500 sm:text-right">
              <p>{board.source}</p>
              <p className="mt-1">{formatDateLabel(board.createdAt)}</p>
            </div>
          </div>
        </header>

        <section className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm">
          <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p className="text-xs font-semibold tracking-wide text-blue-600">
                FINAL GENERATED CHART
              </p>
              <h2 className="mt-1 text-base font-semibold text-gray-900">
                {board.title}
              </h2>
            </div>
            <div className="grid grid-cols-2 gap-2 text-sm">
              <div className="rounded-md bg-gray-50 px-3 py-2">
                <p className="text-xs text-gray-500">{metricLabels.primary}</p>
                <p className="font-semibold text-gray-900">
                  {formatMetricValue(metricKeys.primary, latestRow[metricKeys.primary])}
                </p>
              </div>
              <div className="rounded-md bg-gray-50 px-3 py-2">
                <p className="text-xs text-gray-500">{metricLabels.secondary}</p>
                <p className="font-semibold text-gray-900">
                  {formatMetricValue(metricKeys.secondary, latestRow[metricKeys.secondary])}
                </p>
              </div>
            </div>
          </div>
          <DemoInsightChart data={board.chartData} insight={board} />
          {board.analysisImpact?.chartNote && (
            <p className="mt-4 rounded-md bg-orange-50 px-3 py-2 text-sm leading-6 text-orange-800">
              {board.analysisImpact.chartNote}
            </p>
          )}
        </section>

        <section className="grid gap-4 lg:grid-cols-4">
          {pipeline.map((step, index) => {
            const icons = [Database, FileText, GitBranch, BarChart3];
            const StepIcon = icons[index] || Sparkles;
            return (
            <div key={step.title} className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm">
              <StepIcon className="h-5 w-5 text-blue-600" />
              <h3 className="mt-3 text-sm font-semibold text-gray-900">{step.title}</h3>
              <p className="mt-1 text-xs leading-5 text-gray-500">{step.body}</p>
            </div>
            );
          })}
        </section>

        <section className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm">
          <h2 className="text-base font-semibold text-gray-900">데이터 소스</h2>
          <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
            {[
              ["Provider", sourceMeta.provider],
              ["Table", sourceMeta.table],
              ["Rows", sourceMeta.rowCount],
              ["Status", sourceMeta.status],
              ["Last queried", formatDateLabel(sourceMeta.lastQueriedAt)],
            ].map(([label, value]) => (
              <div key={label} className="rounded-md bg-gray-50 p-3">
                <p className="text-xs text-gray-500">{label}</p>
                <p className="mt-1 text-sm font-semibold text-gray-900">{value}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm">
          <h2 className="text-base font-semibold text-gray-900">AI 분석</h2>
          <div className="mt-4 grid gap-4 lg:grid-cols-[280px_1fr]">
            <div className="rounded-md bg-gray-50 p-4">
              <p className="text-xs font-medium text-gray-500">사용자 질문</p>
              <p className="mt-2 text-sm leading-6 text-gray-900">
                "{board.userPrompt}"
              </p>
            </div>
            <div className="rounded-md bg-blue-50 p-4">
              <p className="text-xs font-medium text-blue-700">RAG 반영 AI 분석 결과</p>
              <p className="mt-2 text-sm leading-6 text-blue-950">
                {board.llmAnswer}
              </p>
              {board.ragSummary && (
                <p className="mt-3 rounded-md bg-white/70 px-3 py-2 text-xs leading-5 text-blue-900">
                  {board.ragSummary}
                </p>
              )}
            </div>
          </div>
        </section>

        {board.analysisImpact?.whyBetter && (
          <section className="rounded-lg border border-orange-200 bg-orange-50 p-5 shadow-sm">
            <div className="flex items-center gap-2 text-base font-semibold text-orange-950">
              <Search className="h-5 w-5 text-orange-600" />
              RAG가 높인 분석 품질
            </div>
            <p className="mt-3 text-sm leading-6 text-orange-900">
              {board.analysisImpact.whyBetter}
            </p>
          </section>
        )}

        {ragEvidence.length > 0 && (
          <section className="rounded-lg border border-orange-200 bg-white p-5 shadow-sm">
            <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
              <div className="flex items-center gap-2 text-base font-semibold text-gray-900">
                <FileText className="h-5 w-5 text-orange-600" />
                차트에 반영된 RAG 원본 데이터
              </div>
              <span className="text-xs font-medium text-orange-700">
                원문 chunk와 차트 구간이 메타데이터로 연결됨
              </span>
            </div>
            <div className="mt-4 grid gap-4 lg:grid-cols-2">
              {ragEvidence.map((item) => (
                <article key={item.id} className="rounded-lg border border-gray-200 bg-gray-50 p-4">
                  <div className="flex flex-wrap items-center gap-2 text-xs">
                    <span className="rounded-full bg-white px-2 py-1 font-medium text-gray-700">
                      {item.source}
                    </span>
                    <span className="rounded-full bg-blue-50 px-2 py-1 font-medium text-blue-700">
                      {item.linkedMonth}
                    </span>
                    <span className="rounded-full bg-orange-50 px-2 py-1 font-medium text-orange-700">
                      similarity {Math.round(item.similarity * 100)}%
                    </span>
                  </div>
                  <h3 className="mt-3 text-sm font-semibold text-gray-900">{item.title}</h3>
                  <p className="mt-2 text-sm leading-6 text-gray-700">
                    "{item.chunkText}"
                  </p>
                  <p className="mt-3 rounded-md bg-orange-50 px-3 py-2 text-xs leading-5 text-orange-800">
                    {item.chartImpact}
                  </p>
                  <div className="mt-3 flex flex-wrap gap-2 text-xs text-gray-600">
                    {Object.entries(item.metadata || {}).map(([key, value]) => (
                      <span key={key} className="rounded bg-white px-2 py-1">
                        {key}: {value}
                      </span>
                    ))}
                  </div>
                </article>
              ))}
            </div>
          </section>
        )}

        {chunkingItems.length > 0 && (
          <section className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm">
            <div className="flex items-center gap-2 text-base font-semibold text-gray-900">
              <Layers3 className="h-5 w-5 text-blue-600" />
              {board.chunkingStrategy.title}
            </div>
            <p className="mt-2 text-sm leading-6 text-gray-600">
              {board.chunkingStrategy.description}
            </p>
            <div className="mt-4 grid gap-3 md:grid-cols-3">
              {chunkingItems.map((item) => (
                <div key={item.label} className="rounded-md bg-gray-50 p-3">
                  <p className="text-sm font-semibold text-gray-900">{item.label}</p>
                  <p className="mt-1 text-xs leading-5 text-gray-600">{item.value}</p>
                </div>
              ))}
            </div>
          </section>
        )}

        <section className="overflow-hidden rounded-lg border border-gray-200 bg-gray-950 shadow-sm">
          <button
            onClick={() => setShowSql((value) => !value)}
            className="flex w-full items-center justify-between gap-3 border-b border-gray-800 px-5 py-4 text-left"
          >
            <div className="flex flex-wrap items-center gap-2">
              <h2 className="text-base font-semibold text-white">실행된 SQL</h2>
              <span className="rounded-full bg-gray-800 px-2 py-1 text-xs font-medium text-gray-300">
                Read Only
              </span>
              <span className="inline-flex items-center gap-1 rounded-full bg-green-900/50 px-2 py-1 text-xs font-medium text-green-200">
                <CheckCircle2 className="h-3.5 w-3.5" />
                실행 성공 · 0.84s
              </span>
            </div>
            {showSql ? (
              <ChevronUp className="h-4 w-4 text-gray-400" />
            ) : (
              <ChevronDown className="h-4 w-4 text-gray-400" />
            )}
          </button>
          {showSql && (
            <>
              <div className="flex justify-end border-b border-gray-800 px-5 py-2">
                <button
                  onClick={handleCopySql}
                  className="inline-flex items-center gap-2 rounded-md border border-gray-700 px-3 py-1.5 text-xs font-medium text-gray-200 hover:bg-gray-900"
                >
                  <Clipboard className="h-3.5 w-3.5" />
                  {copied ? "복사됨" : "Copy SQL"}
                </button>
              </div>
              <pre className="max-h-80 overflow-auto p-5 text-xs leading-6 text-blue-100">
                <code>{board.sql}</code>
              </pre>
            </>
          )}
        </section>

        <section className="rounded-lg border border-gray-200 bg-white shadow-sm">
          <button
            onClick={() => setShowRawData((value) => !value)}
            className="flex w-full items-center justify-between border-b border-gray-200 px-5 py-4 text-left"
          >
            <h2 className="text-base font-semibold text-gray-900">원본 데이터 테이블</h2>
            {showRawData ? (
              <ChevronUp className="h-4 w-4 text-gray-500" />
            ) : (
              <ChevronDown className="h-4 w-4 text-gray-500" />
            )}
          </button>
          {showRawData && (
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200 text-sm">
                <thead className="bg-gray-50">
                  <tr>
                    {rawColumns.map((column) => (
                      <th
                        key={column}
                        className="whitespace-nowrap px-4 py-3 text-left font-medium text-gray-600"
                      >
                        {column}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100 bg-white">
                  {rawRows.map((row, index) => (
                    <tr key={index}>
                      {rawColumns.map((column) => (
                        <td key={column} className="whitespace-nowrap px-4 py-3 text-gray-800">
                          {String(row[column])}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </section>
      </div>
    </div>
  );
}
