import { useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  BarChart3,
  ExternalLink,
  MoreVertical,
  Pencil,
  PlusCircle,
  Trash2,
} from "lucide-react";
import DemoInsightChart from "../query/components/DemoInsightChart";
import {
  formatDateLabel,
  formatMetricValue,
  getDashboardState,
  getInsightMetricKeys,
  getInsightMetricLabels,
  removeDashboardInsight,
  renameDashboardInsight,
} from "../query/demoAiQueryData";

function InsightCard({ board, menuOpen, onOpenMenu, onRename, onRemove }) {
  const navigate = useNavigate();
  const latestRow = board.chartData[board.chartData.length - 1];
  const metricKeys = getInsightMetricKeys(board);
  const metricLabels = getInsightMetricLabels(board);

  const openDetail = () => {
    navigate(`/dashboard/insights/${board.id}`);
  };

  return (
    <article
      role="button"
      tabIndex={0}
      onClick={openDetail}
      onKeyDown={(event) => {
        if (event.key === "Enter") openDetail();
      }}
      className="group relative flex min-h-[440px] cursor-pointer flex-col rounded-lg border border-gray-200 bg-white p-4 shadow-sm outline-none transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-md focus:border-blue-400 focus:ring-2 focus:ring-blue-100"
    >
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <p className="text-xs font-semibold tracking-wide text-blue-600">
            GENERATED CHART
          </p>
          <h2 className="mt-2 line-clamp-2 text-base font-semibold text-gray-900">
            {board.title}
          </h2>
        </div>
        <div className="flex shrink-0 items-center gap-2">
          <span className="rounded-full bg-indigo-50 px-2 py-1 text-xs font-medium text-indigo-700">
            Generated by AI
          </span>
          <button
            onClick={(event) => {
              event.stopPropagation();
              onOpenMenu(menuOpen ? null : board.id);
            }}
            className="rounded-md p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-700"
            title="더보기"
          >
            <MoreVertical className="h-4 w-4" />
          </button>
        </div>
      </div>

      {menuOpen && (
        <div
          onClick={(event) => event.stopPropagation()}
          className="absolute right-4 top-12 z-20 w-40 rounded-md border border-gray-200 bg-white p-1 shadow-lg"
        >
          <button
            onClick={openDetail}
            className="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-xs text-gray-700 hover:bg-gray-50"
          >
            <ExternalLink className="h-3.5 w-3.5" />
            상세 보기
          </button>
          <button
            onClick={() => onRename(board.id)}
            className="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-xs text-gray-700 hover:bg-gray-50"
          >
            <Pencil className="h-3.5 w-3.5" />
            이름 변경
          </button>
          <button
            onClick={() => onRemove(board.id)}
            className="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-xs text-red-600 hover:bg-red-50"
          >
            <Trash2 className="h-3.5 w-3.5" />
            Dashboard에서 제거
          </button>
        </div>
      )}

      <div className="mt-4 flex-1 rounded-md border border-gray-100 bg-gray-50 p-2">
        <DemoInsightChart data={board.chartData} insight={board} compact />
      </div>

      <div className="mt-4 grid grid-cols-2 gap-3">
        <div className="rounded-md bg-gray-50 p-3">
          <p className="text-xs text-gray-500">{metricLabels.primary}</p>
          <p className="mt-1 text-sm font-semibold text-gray-900">
            {formatMetricValue(metricKeys.primary, latestRow[metricKeys.primary])}
          </p>
        </div>
        <div className="rounded-md bg-gray-50 p-3">
          <p className="text-xs text-gray-500">{metricLabels.secondary}</p>
          <p className="mt-1 text-sm font-semibold text-gray-900">
            {formatMetricValue(metricKeys.secondary, latestRow[metricKeys.secondary])}
          </p>
        </div>
      </div>

      <div className="mt-4 border-t border-gray-100 pt-3 text-xs text-gray-500">
        <p className="truncate">{board.source}</p>
        <p className="mt-1">{formatDateLabel(board.createdAt)}</p>
      </div>
    </article>
  );
}

export default function DashboardPage() {
  const navigate = useNavigate();
  const [dashboardState, setDashboardState] = useState(() => getDashboardState());
  const [menuBoardId, setMenuBoardId] = useState(null);

  const boards = dashboardState.boards;

  const handleRename = (boardId) => {
    const board = boards.find((item) => item.id === boardId);
    if (!board) return;
    const nextTitle = window.prompt("Dashboard 카드 이름을 입력하세요", board.title);
    if (!nextTitle?.trim()) return;
    const nextState = renameDashboardInsight(boardId, nextTitle);
    setDashboardState(nextState);
    setMenuBoardId(null);
  };

  const handleRemove = (boardId) => {
    if (!window.confirm("이 Dashboard 카드만 제거할까요?")) return;
    const nextState = removeDashboardInsight(boardId);
    setDashboardState(nextState);
    setMenuBoardId(null);
  };

  return (
    <div className="h-full min-h-0 overflow-y-auto bg-gray-50 p-4 sm:p-6">
      <div className="mx-auto max-w-7xl">
        <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <div className="flex items-center gap-2 text-sm font-medium text-blue-600">
              <BarChart3 className="h-4 w-4" />
              Dashboard
            </div>
            <h1 className="mt-1 text-2xl font-semibold text-gray-900">
              생성된 분석 차트
            </h1>
            <p className="mt-1 text-sm text-gray-500">
              AI Query에서 Dashboard에 추가한 최종 차트 결과물을 모아봅니다.
            </p>
          </div>
          <span className="w-fit rounded-full bg-amber-50 px-3 py-1.5 text-xs font-medium text-amber-700">
            Demo Data
          </span>
        </header>

        {boards.length === 0 ? (
          <section className="mt-6 rounded-lg border border-dashed border-gray-300 bg-white p-10 text-center">
            <BarChart3 className="mx-auto h-12 w-12 text-gray-300" />
            <h2 className="mt-4 text-base font-semibold text-gray-900">
              아직 Dashboard에 추가된 분석 결과가 없습니다.
            </h2>
            <p className="mt-2 text-sm text-gray-500">
              AI Query에서 분석을 생성한 뒤 Dashboard에 추가해보세요.
            </p>
            <button
              onClick={() => navigate("/query")}
              className="mt-5 inline-flex items-center gap-2 rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
            >
              <PlusCircle className="h-4 w-4" />
              AI Query로 이동
            </button>
          </section>
        ) : (
          <section className="mt-6 grid gap-5 [grid-template-columns:repeat(auto-fill,minmax(300px,1fr))]">
            {boards.map((board) => (
              <InsightCard
                key={board.id}
                board={board}
                menuOpen={menuBoardId === board.id}
                onOpenMenu={setMenuBoardId}
                onRename={handleRename}
                onRemove={handleRemove}
              />
            ))}
          </section>
        )}
      </div>
    </div>
  );
}
