apiVersion: v1
kind: Service
metadata:
  name: asklake-backend
  namespace: asklake-dev
spec:
  type: ClusterIP
  selector:
    app: asklake-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000

