#!/usr/bin/env python3
"""Create PH-DATA-3 Product Health 5GB processed-input evidence."""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

import pandas as pd

import product_health_synthetic_smoke as smoke


RUN_ID = "run_product_health_5gb_001"
EVIDENCE_PATH = smoke.EVIDENCE / "product_health_5gb_run_summary.json"
BEHAVIOR_EVIDENCE_FILE = smoke.RAW / "kaggle_ecommerce_behavior/2019-Oct.csv"
CSV_CHUNKSIZE = 1_000_000


def resolved_size(path: Path) -> int:
    return path.resolve().stat().st_size


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, default=str), encoding="utf-8")


def scan_behavior_csv(path: Path) -> dict[str, Any]:
    start = time.perf_counter()
    row_count = 0
    event_counts: dict[str, int] = {}
    for chunk in pd.read_csv(
        path,
        usecols=["event_type"],
        dtype={"event_type": "string"},
        chunksize=CSV_CHUNKSIZE,
    ):
        row_count += len(chunk)
        for event_type, count in chunk["event_type"].value_counts(dropna=False).items():
            key = str(event_type)
            event_counts[key] = event_counts.get(key, 0) + int(count)
        if row_count and row_count % 5_000_000 == 0:
            print(f"scanned behavior rows={row_count:,}")
    duration_ms = int((time.perf_counter() - start) * 1000)
    processed_bytes = resolved_size(path)
    return {
        "source": "behavior",
        "path": str(path),
        "processed_input_bytes": processed_bytes,
        "available_source_bytes": processed_bytes,
        "bytes": processed_bytes,
        "bytes_semantics": "processed_input_bytes",
        "row_count_processed": row_count,
        "row_count_sample": row_count,
        "duration_ms": duration_ms,
        "scan_method": "pandas_read_csv_chunks_event_type_count",
        "event_type_counts": event_counts,
    }


def build_5gb_summary() -> dict[str, Any]:
    smoke.main()
    smoke_summary = read_json(smoke.EVIDENCE / "product_health_run_summary.json")
    catalog = read_json(smoke.CATALOG / "dataset_product_health_gold.json")
    behavior_scan = scan_behavior_csv(BEHAVIOR_EVIDENCE_FILE)

    source_map = {source["source"]: source for source in smoke_summary["sources"]}
    source_map["behavior"] = {
        **source_map["behavior"],
        **behavior_scan,
        "connection_id": "conn_product_health_local_sources",
        "source_dataset_id": "source_ecommerce_behavior_events",
        "processed_input_bytes_status": "measured_by_full_csv_scan",
    }
    for role, source in source_map.items():
        if role == "behavior":
            continue
        source["processed_input_bytes"] = 0
        source["processed_input_bytes_status"] = "not_included_in_5gb_processed_byte_total_for_this_phase"
        source["bytes_semantics"] = "available_source_bytes"

    sources = list(source_map.values())
    processed_input_total_bytes = int(sum(source.get("processed_input_bytes") or 0 for source in sources))
    if processed_input_total_bytes < 5 * 1024**3:
        raise RuntimeError(f"processed input bytes below 5GiB: {processed_input_total_bytes}")

    summary = {
        **smoke_summary,
        "run_id": RUN_ID,
        "pipeline_id": smoke.PIPELINE_ID,
        "status": "succeeded",
        "mode": "5gb_evidence",
        "evidence_mode": "processed_5gb_evidence_run",
        "generated_at": smoke.now_iso(),
        "available_source_total_bytes": int(
            sum(source.get("available_source_bytes", source.get("bytes", 0)) for source in sources)
        ),
        "processed_input_total_bytes": processed_input_total_bytes,
        "processed_input_total_bytes_status": "measured",
        "input_total_bytes": processed_input_total_bytes,
        "input_total_bytes_semantics": "processed_input_bytes",
        "sources": sources,
        "catalog_path": str(smoke.CATALOG / "dataset_product_health_gold.json"),
        "catalog_dataset_id": catalog["dataset_id"],
        "gold_output_path": catalog["storage"]["local_fallback_path"],
        "gold_output_row_count": catalog["metrics"]["row_count"],
        "gold_output_bytes": catalog["metrics"]["bytes"],
        "notes": [
            "PH-DATA-3 measures actual processed input bytes separately from available source inventory.",
            "This run fully scans the 2019-Oct ecommerce behavior CSV and links the evidence to the Product Health Gold output generated by the same runner invocation.",
            "Gold output bytes are aggregate output bytes and are not used as 5GB evidence.",
            "Review, metadata, product catalog, and delivery sources keep smoke/source-inventory evidence in this phase; later runtime hardening can expand processed byte measurement to every source.",
        ],
    }
    return summary


def main() -> None:
    smoke.ensure_dirs()
    summary = build_5gb_summary()
    write_json(EVIDENCE_PATH, summary)
    print(f"Wrote {EVIDENCE_PATH}")
    print(f"processed_input_total_bytes={summary['processed_input_total_bytes']}")
    print(f"gold_output_rows={summary['gold_output_row_count']}")


if __name__ == "__main__":
    main()
